### ISSUE TITLE
Query failed at Database_AddPlayer > Error: Field 'name' doesn't have a default value

### ISSUE THREAD

**Issue by Dragonisser** [tf2td/towerdefense#11]
Most likely the reason why nothing is spawning. I already fixed the issue with no metal because the entries in the database was just downright missing...

[TF2TD > Info] Updated server in database (116.202.174.240:27020)
[TF2TD > Trace] Database_OnServerChecked
[TF2TD > Debug] Successfully initialized server
[TF2TD > Trace] Player_UGetString: iUserId=4, sKey=PLAYER_COMMUNITY_ID, iMaxLength=32
[TF2TD > Debug] Successfully initialized player [PrWh] Dragonisser (76561198039140852)
[TF2TD > Trace] Player_UGetString: iUserId=4, sKey=PLAYER_COMMUNITY_ID, iMaxLength=32
[TF2TD > Error] Query failed at Database_AddPlayer > Error: Field 'name' doesn't have a default value
[TF2TD > Trace] Player_UGetValue: iUserId=4, sKey=PLAYER_METAL_PICK
[TF2TD > Trace] Player_OnDataSet: iUserId=4, iClient=1, sKey=PLAYER_METAL_PICK, iDataType=TDDataType_Integer, iValue=1
[TF2TD > Trace] Set [PrWh] Dragonisser's metal to 1
[TF2TD > Trace] Set [PrWh] Dragonisser's metal to 0
[TF2TD > Trace] Should teleport attacker 8 (-1, WeakScout8) of wave 1 (8 attackers)

**Comment by HurpDurp** [comment]
Hello,

I don't have the time or energy these days to maintain this project but I've added you as a maintainer if you wish to contribute your changes to the original repo instead of a fork.

**Comment by Dragonisser** [comment]
Alright

**Comment by Dragonisser** [comment]
Fixed https://github.com/tf2td/towerdefense/pull/21
