### ISSUE TITLE
Initializing fail

### ISSUE THREAD

**Issue by BucketCDT** [tf2td/towerdefense#20]
Server cannot initialize and stops at error, many details can be given!

```
[TF2TD > Debug] Initializing server
L 07/04/2023 - 18:42:09: [SM] Exception reported: Array index out-of-bounds (index -1, limit 29)
L 07/04/2023 - 18:42:09: [SM] Blaming: towerdefense.smx
L 07/04/2023 - 18:42:09: [SM] Call stack trace:
L 07/04/2023 - 18:42:09: [SM]   [1] Line 106, towerdefense/handler/server.sp::Server_Reset
L 07/04/2023 - 18:42:09: [SM]   [2] Line 26, towerdefense/handler/server.sp::Server_Initialize
L 07/04/2023 - 18:42:09: [SM]   [3] Line 227, D:\TowerDefense\addons\sourcemod\scripting\towerdefense.sp::InitializeDelay
```

**Comment by Dragonisser** [comment]
Need more information.

Sourcemod version
Dependencies version
Map
Database entry for said map

**Comment by BucketCDT** [comment]
Sourcemod version: 1.11.0.6923
Depend Versions: (TF2Items: 1.6.4), (SteamTools: 0.10.0), (Socket: 3.0.1), (TF2Attributes: 1.7.3)
Map: td_firstone_v11b
Map database entry: ('2', 'td_firstone_v11b', '560 -1795 -78 0 90 0', '560 -1795 131 0 90 0', '666 -626 -2 0 0 0', '30', '4', '66', '130')

Hope this helps!

**Comment by BucketCDT** [comment]
![image](https://github.com/tf2td/towerdefense/assets/28717221/59a6fe39-7838-45ca-b978-3c9f02d57851)

Using latest tower defense version? Yes

**Comment by Dragonisser** [comment]
I found why the index is -1 but not why the function cant get the TowerId (which results to -1)

https://github.com/tf2td/towerdefense/blob/master/addons/sourcemod/scripting/towerdefense/handler/server.sp#L105C28-L105C28

https://github.com/tf2td/towerdefense/blob/master/addons/sourcemod/scripting/towerdefense/handler/towers.sp#L589

**Comment by Dragonisser** [comment]
Can you change the loglevel of your server to Debug and try the following file? Restart the server after changing the plugin and loglevel.

Then check the console log or server log and paste it here.

![image](https://github.com/tf2td/towerdefense/assets/4233773/fe9eb497-749f-411c-9371-f076ada83ac7)

[towerdefense.zip](https://github.com/tf2td/towerdefense/files/12291876/towerdefense.zip)

**Comment by BucketCDT** [comment]
[errors_20230808.log](https://github.com/tf2td/towerdefense/files/12292307/errors_20230808.log)

**Comment by Dragonisser** [comment]
Not the error log, the normal log.

**Comment by BucketCDT** [comment]
[L20230808.log](https://github.com/tf2td/towerdefense/files/12292487/L20230808.log)
Sorry my bad

**Comment by BucketCDT** [comment]
And here is a whole runtime console view

**Comment by BucketCDT** [comment]
I do not have a required 32bit binary, is that an issue for this plugin?

**Comment by Dragonisser** [comment]
Doubt. Im more confused why it isn't showing any of my debug information. Did you download the attached .smx and replaced it with the current one?

If it was mine, it would show a lot more information and it shouldn't even crash anymore.

**Comment by Dragonisser** [comment]
According to the error its still in the same line which makes no sense and your version isn't the one of me, which should be 2.1.0

[TF2TD] Loaded TF2 Tower Defense 2.0.2 by floube, benedevil, hurpdurp

**Comment by BucketCDT** [comment]
huh

**Comment by Dragonisser** [comment]
What i also dont understand is why are there bots on your server already before towerdefense is even initialised?

**Comment by BucketCDT** [comment]
Sorry for the wait, but here

**Comment by BucketCDT** [comment]
It just keeps saying the same message so I ended it early

**Comment by BucketCDT** [comment]
You think tf_bot_quota being set, is causing this?

**Comment by BucketCDT** [comment]
Very much sorry for wasting your time, thanks for telling me that

**Comment by Dragonisser** [comment]
Yes. Because its adds bots in the defender team which causes the plugin to think its a tower. But since it isn't it breaks.

Glad it works now. Ill see if i can add some safety measurements to prevent that in the future.
