### ISSUE TITLE
Cant İmport Database

### ISSUE THREAD

**Issue by MasterMister** [tf2td/towerdefense#33]
Hata
Sabit çözümleme:

Çözümleme sırasında 6 hata bulundu.

Beklenmeyen ifade başlangıcı. (near "131" at position 1)
Beklenmeyen ifade başlangıcı. (near "7" at position 6)
Beklenmeyen ifade başlangıcı. (near "'dragonisser'" at position 9)
Beklenmeyen ifade başlangıcı. (near "'Medic'" at position 24)
Beklenmeyen ifade başlangıcı. (near "12" at position 33)
Beklenmeyen ifade başlangıcı. (near "8000" at position 37)
SQL sorgusu: [Kopyala](http://localhost/phpmyadmin/index.php?route=/import#)

(131, 7, 'dragonisser', 'Medic', 12, 8000);

MySQL çıktısı: Belgeler

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '131, 7, 'dragonisser', 'Medic', 12, 8000)' at line 1

**Comment by Dragonisser** [comment]
It would be great if you write english.
