### ISSUE TITLE
Bots and ammo packs won't spawn

### ISSUE THREAD

**Issue by Dovahkiin-Warrior** [tf2td/towerdefense#4]
Pretty much sums it up. I've tried sourcemod 1.8 and 1.9 both, to no avail. Bots won't spawn and ammo packs won't spawn. I've imported the SQL file and set up the database and database connection is valid, just no ammo packs or bots are spawning at all.

**Comment by kakolisgay** [comment]
Any output from the server?

**Comment by HurpDurp** [comment]
Looks like the solution was to make sure `towerdefense.cfg` was getting executed on map start. Closing this issue.
