### ISSUE TITLE
[SM] Failed to load plugin "towerdefense.smx": [2003]: Can't connect to MySQL server on 'example.com' (10060).

### ISSUE THREAD

**Issue by Newbie123101** [tf2td/towerdefense#44]
## Version of TF2 Tower Defense and dependencies

*For example:*

Tower Defense:          2.1.0

TF2Items:               1.6.4-279

SteamWorks:             1.2.4

TF2Attributes:          v1.7.3

MySQL/MariaDB server:   10.3.39-MariaDB-0+deb10u1

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, E.g.

1. Join a server
2. Join a team
3. Start the wave
4. Bots dont spawn

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"

## Evidence (optional)

Show us what happened or provide any kind of logs

**Comment by Dragonisser** [comment]
Fill out the form and read the guide. The error is quite clear.
