### ISSUE TITLE
sv_cheats

### ISSUE THREAD

**Issue by rumblefrog** [tf2td/towerdefense#6]
So it seems like the plugin silently turns on sv_cheats but I'm not sure what its use is if I may be enlightened on that topic.

Currently, I have some players using noclip, addcond, etc to help them pass the round that seems unfair in my opinion.

**Comment by HurpDurp** [comment]
Yes, the plugin does set sv_cheats on when it is active. I'm not entirely
sure the technical reason, it probably has to do with bots needing some
special configuration.

On servers I ran in the past, we always used a sourcemod plugin that masked
that value (cheat control?) so the server could run with it on but to
clients it would appear to be off.

**Comment by HurpDurp** [comment]
I just checked and we were using this plugin:

https://forums.alliedmods.net/showthread.php?p=2043735

With this configuration:

```
"ConVar_Faker"
{
	"sv_cheats"
	{
		"value"			"0"
	}
}
````

**Comment by rumblefrog** [comment]
Thanks, I applied the fix to my fork.
